//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }
        public int ProductKey { get; set; }
        public virtual Product Product { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }

        public int SaleKey { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> CustomerKey { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Person Person { get; set; }
        public int SaleDetailKey { get; set; }
       
        public int SaleDetailQuantity { get; set; }
        public Nullable<decimal> SaleDetailDiscount { get; set; }
        public Nullable<decimal> SaleDetailSaleTaxPercent { get; set; }
        public Nullable<decimal> SaleDetailEatInTax { get; set; }

        public virtual Sale Sales { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
